# main
close_enough: 0.05
target_dt: 0.04 # this (s) should be slower than or equals to main_iter_rate (Hz)
average_speed: 0.2
cell_size: 0.04
inflation_radius: 0.22
log_odds_thresh: 10 # this should be smaller than log_odds_cap
log_odds_cap: 20
main_iter_rate: 25 

# motion
verbose_motion: false
use_internal_odom: false
axle_track: 0.16
wheel_radius: 0.033
weight_odom_v: 0.5
weight_odom_w: 0.5
straight_thresh: 0.05
motion_iter_rate: 50

# move
enable_move: true
verbose_move: false
Kp_lin: 2.0
Ki_lin: 0
Kd_lin: 0.3
max_lin_vel: 0.10 # max is 0.22
max_lin_acc: 1
Kp_ang: 2.0
Ki_ang: 0
Kd_ang: 0.3
max_ang_vel: 0.5 # max is 2.84
max_ang_acc: 4
move_iter_rate: 25
